### PR TITLE
Prefix opcodes with $

### PR DESCRIPTION
**Pull request by InsaneFirebat**
I was trying to lookup which instruction used the DA opcode and had a hard time finding it through all the text. I decided to prefix all of the opcodes with $ so they can easily be searched.

Thank you for this resource. It and the register page are some of my most used references. Feel free to close this if you'd rather do it yourself or not at all.

### CODE REVIEW

**Comment by InsaneFirebat** [comment]
Force-pushed a fix for the special JMP and WDM tables. Missed them on the first pass.

**Comment by undisbeliever** [comment]
This sounds like a good idea.

I just realised I never gave these pages a license.  I thinking of using the [Creative Commons Attribution–ShareAlike (CC BY-SA) License](https://creativecommons.org/licenses/by-sa/4.0/), and if I accept this PR that would make you a contributor.

Would you be happy with me licensing this contribution under CC-BY-SA?

I will include an attribution on the 65816 opcodes page if you accept (it would be something along the lines of "*Copyright © 2019 undisbeliever with contributions by [InsaneFirebat](https://github.com/InsaneFirebat), licensed under CC-BY-SA*").

**Comment by InsaneFirebat** [comment]
That's all fine with me, thanks.

**Comment by undisbeliever** [comment]
Merged and uploaded to my website (with the new copyright and license text).

<br/>

> Thank you for this resource. It and the register page are some of my most used references.

And thank you for the kind words.  It's always encouraging to know that people are making use of my works.

**Pull request merged**
